---
apiVersion: tower.ansible.com/v1alpha1
kind: AnsibleJob
metadata:
  name: prejob
spec:
  tower_auth_secret: ansible-tower
  job_template_name: Logger
  extra_vars:
    trigger_name: mariadb
    hook_type: prehook
    log_file_name: rhacm.log